steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/storage/cloudbuild.yaml', '.']
    id: 'storage'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/datafusion_platform/cloudbuild.yaml', '.']
    id: 'datafusion_platform'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/datafusion_staging/cloudbuild.yaml', '.']
    id: 'datafusion_staging'