steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/platform/storage/cloudbuild.yaml', '.']
    id: 'raw_bucket'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/staging/storage/cloudbuild.yaml', '.']
    id: 'storage_platform'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/platform/datafusion_platform/cloudbuild.yaml', '.']
    id: 'datafusion_platform'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaaC/Modulos/staging/datafusion_staging/cloudbuild.yaml', '.']
    id: 'datafusion_staging'